language: ruby
rvm:
  - 2.1

# branch whitelist
branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_script:
  - bundle update

script:
  - bundle exec jekyll build --drafts
  - bundle exec htmlproof ./_site

notifications:
  email: true
