# Site settings
title: NetLicensing
email: info@labs64.com
description: Labs64 NetLicensing is a first-class solution in the Licensing-as-a-Service (LaaS) sector.
keywords: netlicensing,software license,licensing model,license types,license management,Licensing-as-a-Service,software activation,subscription,floating
copyright: Labs64 GmbH
company: Labs64
company_url: "https://www.labs64.com"

url: "http://netlicensing.io"
# subpath of the site, e.g. /blog/
baseurl: ""

dns_prefetch:
 - https://go.netlicensing.io
 - //www.labs64.de
 - //www.labs64.com
 - //io.labs64.com
 - //l64.cc

# Styling
stage_banner_image: "../img/netlicensing-stage-banner-01.png"

# Blog
blog_placeholder_image: "/img/blog/blog-placeholder.jpg"
blog_recommended_posts:
 - /blog/2016/01/22/labs64-netlicensing-2-3-is-out/
 - /blog/2015/10/24/infographic-how-to-select-licensing-model/
 - /blog/2015/04/02/services-can-add-automatic-image-attribution-for-your-website/

# Ads
ads_hiring_text: We Are Hiring!
ads_hiring_url: "http://www.labs64.com/career/software-developer-javaee-mf-116-l64-17/"

# SEO
google_author: "https://plus.google.com/+NetlicensingIoLabs64"
google_analytics_tracking_id: "UA-32654174-2"
quantcast_code: "p-RQ36fR9PJnAcZ"
yandex_metrika_tracking_id: "33072638"
disqus_shortname: "netlicensing"

# Build settings
markdown: kramdown
highlight: rouge
permalink: /blog/:year/:month/:day/:title/

# Sass
sass:
  sass_dir: _scss
  style: :compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []

# Exclude these files from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .gitignore

# Custom collections
collections:
  case-studies:
    output: true

defaults:
  -
    scope:
      path: ""              # an empty string here means all files in the project
      type: "case-studies"
    values:
      layout: "casestudy"
      show_meta: true       # Show metadata beneath all pages
      author: "Labs64"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      show_meta: true
      author: "Labs64"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_meta: true
      author: "Labs64"
