- title: "Contact"
  url: "/contact/"
  class: "services-contact"

- title: "RSS"
  url: "/feed.xml"
  class: "rss-link"

- title: "Sitemap"
  url: "/sitemap.xml"
  class: "sitemap-link"

- title: "Imprint"
  url: "http://www.labs64.com/imprint/"
  class: "imprint-link"
