# About&Connect
- title: "About"
  url: "https://www.labs64.com/about-us/"
  section: "Company"

- title: "Partners"
  url: "https://www.labs64.com/netlicensing/partners/"
  section: "Company"

- title: "Contact"
  url: "/contact/"
  section: "Company"

# Learn
- title: Getting Started
  url: "/getting-started/"
  section: "Documentation"

- title: Case Studies
  url: "/case-studies/"
  section: "Documentation"

- title: For Integrators
  url: "/documentation/"
  section: "Documentation"

- title: Pricing
  url: "/pricing/"
  section: "Documentation"

- title: Journal
  url: "/blog/"
  section: "Documentation"

# Legal
- title: "Terms of Service"
  url: "http://www.labs64.com/legal/terms-of-service/netlicensing/"
  section: "Legal"

- title: "Service Level Agreement"
  url: "http://www.labs64.com/legal/terms-of-service/netlicensing/service-level-agreement-1-0/"
  section: "Legal"

- title: "Privacy Policy"
  url: "http://www.labs64.com/legal/privacy-policy/"
  section: "Legal"

- title: "Cookies Policy"
  url: "http://www.labs64.com/legal/privacy-policy/cookies-policy/"
  section: "Legal"

- title: "Privacy Center"
  url: "https://www.labs64.de/confluence/x/vQEKAQ"
  section: "Legal"

- title: "Imprint"
  url: "http://www.labs64.com/imprint/"
  section: "Legal"
